name: one_click_builder
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+17

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
#  State management technic
  provider: ^6.1.2
#  Animated page transfer
  page_transition: ^2.1.0
# Local data storage
  shared_preferences: ^2.5.2
#  Country peckerP
  country_picker: ^2.0.27
  svg_flutter: ^0.0.1
  dotted_border: ^2.1.0
  dotted_line: ^3.2.2
  flutter_switch: ^0.3.2
  flutter_dash: ^1.0.0
  flutter_rating_bar: ^4.0.1
  percent_indicator: ^4.2.3
  flutter_localization: ^0.2.0
  flutter_html: ^3.0.0
  dio: ^5.8.0+1
  countries_utils: ^1.0.1
  country_state_city_picker: ^1.2.8
  pinput: ^5.0.1
  google_fonts: ^6.3.0
  html: ^0.15.6
  get: ^4.7.2
  carousel_slider: ^5.1.1
  smooth_page_indicator: ^1.1.0
  shimmer: ^2.0.0
  flutter_bloc: ^9.1.1
  image_picker: ^1.0.7
  device_preview: ^1.1.0
  shimmer_animation: ^2.2.2+1
  csc_picker_plus: ^0.0.3
  intl_phone_field: ^3.2.0
  country_code_picker: ^3.4.1

  


  
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^5.0.0
  http: ^1.2.2

flutter_icons:
  android: true
  ios: true
  image_path: assets/logo.png
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/image/
    - assets/svg/
    - assets/india/Indian_Cities_In_States_JSON
    - assets/cart.gif
    - assets/shopingcart.gif
    - assets/nexus.png
    - assets/loader_hd.gif


fonts:
      - family: Poppins
        fonts:
          - asset: assets/font/poppins/Poppins-Regular.ttf
            weight: 400
          - asset: assets/font/poppins/Poppins-Medium.ttf
            weight: 500
          - asset: assets/font/poppins/Poppins-SemiBold.ttf
            weight: 600
      - family: Optima LT
        fonts:
          - asset: assets/font/Optima/Optima LT Bold.ttf
            weight: 600    
